default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: payroll-360_development

test:
  <<: *default
  database: payroll-360_test

production:
  <<: *default
  database: payroll-360_production
  username: payroll-360
  password: <%= ENV['PAYROLL-360_DATABASE_PASSWORD'] %>
